### ISSUE TITLE
Suggestion: Method to read AssemblyTitleAttribute

### ISSUE THREAD

**Issue by YipYipX4** [laazyj/ApplicationAssemblyUtility#6]
I've used code from your StackOverflow post, plus code from the following post to create a reusable splash screen for multiple intranet web sites (the splash screen includes the title and version number).

You might like to include this helper in your library too:
http://stackoverflow.com/questions/7320078/read-assemblytitle-attribute-in-asp-net

**Comment by laazyj** [comment]
Thanks for the suggestion. I'm not doing any active development on this project but would accept a pull request if you sent one.
