### ISSUE TITLE
ApplicationAssembly returns wrong assembly when called inside WCF application

### ISSUE THREAD

**Issue by Texernie** [laazyj/ApplicationAssemblyUtility#9]
If ApplicationAssemblyUtility.ApplicationAssembly is called from within a WCF service, it will return the assembly for ApplicationAssemblyUtility instead of the WCF's assembly. 

This is due to HttpContext.Current being null when called from a WCF service. (http://stackoverflow.com/questions/5990479/httpcontext-in-wcf)

**Comment by laazyj** [comment]
Changes included in NuGet version 1.2.1.16
